### ISSUE TITLE
Wrong radius on icon

### ISSUE THREAD

**Issue by basvdploeg** [athombv/homey-mac-app#10]
The app icon is using a wrong corner radius, or more particular: it's not using "smooth corners". A minor detail, but still. 😜

Also the shadows are not exactly right.

This could be an alternative:

![Homey](https://user-images.githubusercontent.com/4628469/103178303-f139a500-4881-11eb-886a-64b381b81370.png)

Exports: 
[Homey macOS icon.zip](https://github.com/athombv/homey-mac-app/files/5745078/Homey.macOS.icon.zip)

Sketch: 
[Homey macOS icon sketch.zip](https://github.com/athombv/homey-mac-app/files/5745080/Homey.macOS.icon.sketch.zip)

**Comment by WeeJeWel** [comment]
Very nice, thank you! It has been added to Release 3.
